//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLDAG.Libraries.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CGR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CGR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TLDAG.Libraries.Core.Resources.CGR", typeof(CGR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC001 Invalid state: Alphabet not set..
        /// </summary>
        internal static string SC001_AlphabetNotSet {
            get {
                return ResourceManager.GetString("SC001_AlphabetNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC002 Invalid state: Transitions not initialized..
        /// </summary>
        internal static string SC002_TransitionsNotInitialized {
            get {
                return ResourceManager.GetString("SC002_TransitionsNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC003  Invalid state: Transitions not set..
        /// </summary>
        internal static string SC003_TransitionsNotSet {
            get {
                return ResourceManager.GetString("SC003_TransitionsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC004 Illegal argument: Wrong ransitions length (expected {0}, actual {1})..
        /// </summary>
        internal static string SC004_InvalidTransitionsLength {
            get {
                return ResourceManager.GetString("SC004_InvalidTransitionsLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC100 Invalid state: Tree stack has not exactly one entry..
        /// </summary>
        internal static string SC100_RexTreeStackNotOne {
            get {
                return ResourceManager.GetString("SC100_RexTreeStackNotOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC101 Invalid state: Tree stack has not enough entries. Expected at least {0} entry/entries..
        /// </summary>
        internal static string SC101_RexTreeNotEnoughEntries {
            get {
                return ResourceManager.GetString("SC101_RexTreeNotEnoughEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC102 Invalid state: Must have at least one tree to create a forest..
        /// </summary>
        internal static string SC102_RexForestEmpty {
            get {
                return ResourceManager.GetString("SC102_RexForestEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC103 Invalid argument: The forest already contains a tree named &apos;{0}&apos;..
        /// </summary>
        internal static string SC103_RexForestDuplicateName {
            get {
                return ResourceManager.GetString("SC103_RexForestDuplicateName", resourceCulture);
            }
        }
    }
}
